name: Deploy FloreDesigns

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v3

    - name: Validar PHP
      run: php -v

    - name: Proyecto listo
      run: echo "Deploy exitoso"